insert into Author values(1, 'kartikey', 'Feminism', 153)
insert into Author values(2, 'Jaya' ,'Machine Learning', 33)
insert into Author values(3, 'Karthik' ,'Android', 43)
insert into Author values(4, 'Bari' ,'xyz', 233)
insert into Author values(5, 'Kartikey' ,'abc', 223)
insert into Author values(6, 'Kartikey' ,'buy', 123)
